# 이 파일은 User's Microservice 에서 사용됩니다
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQA1UUKfpbQHUL3hhOQC37aXfVh9Rnw+6e6fi+HN8W+jV2ThNbJDfXfCbCN9HD+3V5eDe44XqOjHQdk0s9a2JvaoKdWzOWFzt5IJiocSQldJ+7PPjoAeQp73bgVW/4cGwKVQnaGDc3oI9+n9tyVM0uDISBLf0EMvPC6Co2TJBDiV4oQ7aM3cJ5SoCLbVQw2/ODWseU2LalJC/oiGl3yjjKdHdJDatL6Cjg9dZoqfE7N6SFThfmwcLDyrOv8Vbg3nk8cN3K/QWVZTfYjk2N6jqVbsMwN/T+KrcY0nKGH7u0+4QnO4lCYG/J2u4JCR2qqgWaLHJwGQx+OvsNzvsyANcjz/QFBckzwUgyoKTO99HwXNumDh8VUZD0nPbVYWXAELsSY='
    
token:
  expiration_time: 86400000
  secret: '{cipher}AQABTkN5biIvJbv4+xi/m4EYQPfQ6a0oPo2HDBHnMhfJ1D0WQNIS39ne7qXa6KRsav5qvJW+s4g/I9H7NLECnQQbDYqTnfPueeG17v2wVPr3WHMzOzqd1XQxqH11XDNBpD9QnfFT9QcbKsSU/M0Qki8tsLLPxxIk+X28qrClQpMkDoqjrHyFPTXb3401ifBSCMsO9zm9w+yIQkwMSbzAYybDh92vvTreOjmImoQDWSdc1hg6Q9dlz1uCgWNDUBLpepB2YBAghpyHqtd7a+aS1fm78YogaOW20q2vA9+Z1S9Wg+smic77LBLvrexZ/DIutM5CGSvY5eI0K0BYlHusqScLZajlXlO6iXn5sqAQyTWlGG+E2JDWF5b3DtchxbOTGw18MxUA/2sFMhL1oTnrxNXp'
  
gateway:
  ip: 172.18.0.1
  
order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order_is_empty: User's orders is empty.